FROM node:lts-bullseye AS builder
WORKDIR /app

ARG REACT_APP_API_URL
ARG REACT_APP_MANAGE_API_URL
ARG REACT_APP_CHAT_URL
ARG REACT_APP_TITTLE_BASE
ARG REACT_APP_SYSTEM_LOGIN_KEY
ARG REACT_APP_SYSTEM_LOGIN_PASSWORD

ENV GENERATE_SOURCEMAP=false
ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_MANAGE_API_URL=$REACT_APP_MANAGE_API_URL
ENV REACT_APP_CHAT_URL=$REACT_APP_CHAT_URL
ENV REACT_APP_TITTLE_BASE=$REACT_APP_TITTLE_BASE
ENV REACT_APP_SYSTEM_LOGIN_KEY=$REACT_APP_SYSTEM_LOGIN_KEY
ENV REACT_APP_SYSTEM_LOGIN_PASSWORD=$REACT_APP_SYSTEM_LOGIN_PASSWORD

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html

RUN find /usr/share/nginx/html -name "*.map" -type f -delete

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
